name: Github pages deploy

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
    paths:
      - "website/**"
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm ci
      - run: cd website && npm ci && npm run export

      - name: Commit docs changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "docs: update defaults"
          add: "*.md"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist_website
