name: Github pages deploy

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment
    paths:
      - "packages/rececss-website/**"
      - "packages/rececss-core/docs/**"
      - "packages/rececss-components-react/**"
      - "packages/rececss-components-vue/**"
      - "packages/rececss-components-vanilla/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g npm@^7.21.0
      - run: npm -v
      - run: npm ci
      - run: npm run build:website

      - name: Commit docs changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "docs: update defaults"
          add: "*.md"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/rececss-website/dist
